#!/usr/bin/env python
"""PreToolUse hook: block writes to protected, integrity-critical files.

Contract (Claude Code hooks):
  - Reads the hook event JSON from stdin.
  - Inspects tool_input.file_path for the Edit/Write being attempted.
  - If the target is a protected path -- the evaluation golden set
    (datasets/golden.jsonl or data/**/golden.jsonl), any .env / .env.* secret
    file, or a reproducibility-provenance meta.json -- it BLOCKS the write:
    exit code 2, with the reason written to stderr so Claude sees why and can
    route around it. Silently mutating the golden labels or the provenance
    would invalidate every eval number the repo reports.
  - Otherwise exits 0 and lets the write proceed.
  - Degrades gracefully: malformed / empty stdin or any unexpected error -> exit 0
    (fail open; do not wedge the session on a parse error).

Windows-safe: invoked as `python .../protect_golden_and_secrets.py`. Path
matching is done with pathlib on normalized, forward-slashed parts, so it works
regardless of whether Claude passes C:\\Users\\... or ./datasets/golden.jsonl.
No bash-only syntax.

Exit codes:
  0  -> allow (not a protected path, or could not determine -> fail open).
  2  -> block; stderr explains the reason (becomes Claude's feedback).
"""
from __future__ import annotations

import json
import sys
from pathlib import PurePosixPath

# Basenames that are always protected wherever they appear.
PROTECTED_BASENAMES = {
    "golden.jsonl",  # the evaluation golden set / labels
    "meta.json",     # reproducibility provenance (env versions + git SHA + corpus SHA-256)
}


def _read_event() -> dict:
    try:
        raw = sys.stdin.read()
    except Exception:
        return {}
    if not raw or not raw.strip():
        return {}
    try:
        data = json.loads(raw)
    except (ValueError, TypeError):
        return {}
    return data if isinstance(data, dict) else {}


def _extract_file_path(event: dict) -> str | None:
    tool_input = event.get("tool_input")
    if not isinstance(tool_input, dict):
        return None
    fp = tool_input.get("file_path")
    if isinstance(fp, str) and fp.strip():
        return fp
    return None


def _normalize(file_path: str) -> PurePosixPath:
    # Normalize Windows separators to '/' so PurePosixPath part matching is
    # consistent across OSes and however Claude formatted the path.
    unified = file_path.replace("\\", "/")
    return PurePosixPath(unified)


def _protected_reason(file_path: str) -> str | None:
    path = _normalize(file_path)
    name = path.name.lower()
    parts_lower = [p.lower() for p in path.parts]

    # 1) Always-protected basenames (golden set, provenance meta.json).
    if name in PROTECTED_BASENAMES:
        if name == "golden.jsonl":
            return (
                "Blocked: '{p}' is the evaluation GOLDEN SET. Agents must never "
                "silently mutate the golden labels -- doing so invalidates every "
                "recall@k / nDCG@k / MRR number the repo reports. If the golden "
                "set genuinely needs to change, a human must do it deliberately "
                "(and re-run /eval-report afterwards).".format(p=file_path)
            )
        return (
            "Blocked: '{p}' is a reproducibility PROVENANCE file (meta.json: env "
            "versions + git SHA + corpus SHA-256). It must be regenerated by the "
            "index/eval build, never hand-edited by an agent -- editing it breaks "
            "bit-exact reproducibility.".format(p=file_path)
        )

    # 2) Secret files: .env and .env.<anything>.
    if name == ".env" or name.startswith(".env."):
        return (
            "Blocked: '{p}' is a secrets file (.env). Agents must not create or "
            "modify environment/secret files.".format(p=file_path)
        )

    # 3) Defense in depth: anything under a 'datasets' or 'data' dir literally
    #    named golden.jsonl is already caught above by basename; this also
    #    catches versioned variants like golden.v2.jsonl living in those dirs.
    in_data_dir = any(part in ("datasets", "data") for part in parts_lower)
    if in_data_dir and name.startswith("golden") and name.endswith(".jsonl"):
        return (
            "Blocked: '{p}' looks like an evaluation golden set under a data "
            "directory. Golden labels must not be mutated by an agent.".format(p=file_path)
        )

    return None


def main() -> int:
    event = _read_event()
    file_path = _extract_file_path(event)
    if not file_path:
        # Could not determine a target path -> fail open, let other layers decide.
        return 0

    try:
        reason = _protected_reason(file_path)
    except Exception:
        return 0

    if reason:
        sys.stderr.write(reason + "\n")
        return 2

    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception:
        # Fail open: a crash in the guard must not wedge the whole session.
        sys.exit(0)
